/**
 * Deterministic Playwright `.spec.ts` generation from a recorded session
 * (spec §9.10). The skeleton is template-based so the output always compiles;
 * the server may run an optional LLM pass afterwards to enrich comments and
 * assertions. Fragile selectors are flagged with TODO comments + warnings.
 */

import type { ActionEvent, TestSession } from './types.js';
import { escapeForSingleQuotes, isFragileLocator } from './selector.js';

export interface SelectorWarning {
  eventId: string;
  targetLabel?: string;
  locator: string;
  message: string;
}

export interface PlaywrightSpec {
  filename: string;
  content: string;
  selectorWarnings: SelectorWarning[];
}

function slugify(input: string, fallback: string): string {
  const slug = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug.length > 0 ? slug : fallback;
}

function lit(value: string): string {
  return `'${escapeForSingleQuotes(value)}'`;
}

/** Pick the best (first) locator for an event, falling back to text/role by label. */
function locatorFor(ev: ActionEvent): { expr: string; fragile: boolean } {
  const best = ev.selectorCandidates?.[0];
  if (best) {
    return { expr: `page.${best}`, fragile: isFragileLocator(best) };
  }
  if (ev.targetLabel) {
    // No recorded candidate — fall back to text and flag it.
    return { expr: `page.getByText(${lit(ev.targetLabel)})`, fragile: true };
  }
  return { expr: `page.locator('body')`, fragile: true };
}

function stepForEvent(ev: ActionEvent, warnings: SelectorWarning[]): string[] {
  const lines: string[] = [];
  const pushFragile = (expr: string) => {
    lines.push(`  // TODO: fragile selector — add a data-testid for a stable locator`);
    warnings.push({
      eventId: ev.id,
      targetLabel: ev.targetLabel,
      locator: expr,
      message: 'Fragile selector (CSS/XPath/text fallback). Prefer data-testid or role+name.',
    });
  };

  if (ev.type === 'navigation') {
    // Initial goto is emitted by the caller; later navigations become a wait.
    if (ev.value) lines.push(`  await page.waitForURL(${lit(ev.value)});`);
    return lines;
  }

  const { expr, fragile } = locatorFor(ev);
  if (fragile) pushFragile(expr);

  switch (ev.type) {
    case 'click':
      lines.push(`  await ${expr}.click();`);
      break;
    case 'submit':
      lines.push(`  await ${expr}.click();`);
      break;
    case 'input':
      if (ev.value === undefined) {
        // Sensitive / unrecorded value.
        lines.push(`  // TODO: provide a value (sensitive input was not recorded)`);
        lines.push(`  await ${expr}.fill('');`);
      } else {
        lines.push(`  await ${expr}.fill(${lit(ev.value)});`);
      }
      break;
    case 'select':
      if (ev.valueType === 'aria-option') {
        // Custom (ARIA) dropdown — not a native <select>; selectOption would throw.
        // Open the control, then click the option by its visible name.
        lines.push(`  await ${expr}.click();`);
        lines.push(
          `  await page.getByRole('option', { name: ${lit(ev.valueText ?? ev.value ?? '')} }).click();`,
        );
      } else {
        // Native <select> — Playwright matches an <option> by value or label.
        lines.push(`  await ${expr}.selectOption(${lit(ev.valueText ?? ev.value ?? '')});`);
      }
      break;
    case 'checkbox':
      lines.push(`  await ${expr}.${ev.value === 'false' ? 'uncheck' : 'check'}();`);
      break;
    case 'radio':
      lines.push(`  await ${expr}.check();`);
      break;
    case 'screenshot':
      lines.push(`  await page.screenshot({ path: ${lit((ev.value ?? 'step') + '.png')} });`);
      break;
  }

  // Turn an observed validation/result into an assertion.
  if (ev.resultSummary && /error|required|invalid|success|saved|appeared/i.test(ev.resultSummary)) {
    lines.push(`  await expect(page.getByText(${lit(ev.resultSummary)})).toBeVisible();`);
  }
  return lines;
}

export function buildPlaywrightSpec(session: TestSession): PlaywrightSpec {
  const warnings: SelectorWarning[] = [];
  const title = session.currentUrl ?? session.baseUrl ?? 'recorded flow';
  const testName = `recorded flow: ${title}`;
  const filename = `${slugify(title, 'recorded-flow')}.spec.ts`;

  const body: string[] = [];
  const gotoUrl = session.baseUrl ?? session.currentUrl;
  if (gotoUrl) body.push(`  await page.goto(${lit(gotoUrl)});`);

  for (const ev of session.events) {
    const lines = stepForEvent(ev, warnings);
    if (lines.length > 0) {
      body.push(
        '',
        // Auto Test Mode records the model's stated intent per action
        // (auto-test-mode-spec §11) — surface it above the step.
        ...(ev.intent ? [`  // intent: ${ev.intent}`] : []),
        `  // ${ev.type}${ev.targetLabel ? `: ${ev.targetLabel}` : ''}`,
        ...lines,
      );
    }
  }

  const content = `import { test, expect } from '@playwright/test';

// DRAFT — generated by QA Copilot from a recorded manual QA session.
// Review selectors and assertions before adding to a suite.
test(${lit(testName)}, async ({ page }) => {
${body.join('\n')}
});
`;

  return { filename, content, selectorWarnings: warnings };
}
